baseURL = 'https://yuvarajk7.github.io/'
languageCode = 'en-us'
title = 'Yuvaraj Kesavan'
theme = "anubis"
paginate = 3

[author]
name = "Yuvaraj Kesavan"

[params]
author = "Yuvaraj Kesavan"
description = "Personal Blog Post"
dateFormat = "2006-01-02"
paginationSinglePost = true
style = "auto"
readMore = false
readNextPosts = 2
copyCodeButton = true
rssAsSocialIcon = true
mathjax = false